### PR TITLE
More helper methods - `from_bytes` and `from_io`

### PR DESCRIPTION
**Pull request by GreyCat**
This PR adds more helper methods to make generated classes from accessible without diving deep into intricacies of Kaitai Struct from the very beginning. Akin to `from_file`, these are to be used:

* `from_bytes` - to parse an object from a `bytes` type, i.e. raw byte array
* `from_io` - to parse an object from any instance of Python's [IO stream object](https://docs.python.org/3/library/io.html), which can be a in-memory stream, file, socket, etc

Just some tiny wrappers that make life easier.

Cc @koczkatamas @felixonmars @dgladkov @KOLANICH

### CODE REVIEW

**Comment by koczkatamas** [comment]
Looks good to me :+1:

**Comment by GreyCat** [comment]
Merging it up, then.

**Comment by arekbulski** [comment]
Could you remove the stale branch, please?
https://github.com/kaitai-io/kaitai_struct_python_runtime/branches

**Comment by GreyCat** [comment]
Thanks!

**Pull request merged**
