### PR TITLE
KaitaiStream code cleanup

### PR DESCRIPTION
**Pull request by arekbulski**
Those are just to make code readable/pythonic. I dont know how to run the benchmarks on this code so no performance guarantees, although it should be comparable.

### CODE REVIEW

**Comment by GreyCat** [comment]
I'm slightly concerned about performance of these `process_*` routines. @dgladkov did some benchmarking and suggested current solution as optimal. I believe you've started some work on Python benchmarks, so may be we should return to it after you'll be happy with the results?

**Comment by arekbulski** [comment]
The difference is small, it does not warrant complexity of current implementation. I am familiar with his changes, read #8 . If you really want to speed it up, we need Cython for that. Those are just superficial speedups. 

I know where the benchmarks repo is but I dont know how to run it against a PR. I would require some assistance with that.

**Comment by arekbulski** [comment]
I suggest we merge it now, and return to processxor performance when there is nothing better to do.

**Comment by arekbulski** [comment]
Forgive me for merging my own PR, we can get back to this topic when Cython gets added.

**Pull request merged**
